export const ROLES = ["ADMIN", "TIP_REVIEWER", "SUPER_ADMIN"];

export const PERMISSIONS = [
  "CASE_READ_ALL", "CASE_ADMIN_CREATE", "CASE_ADMIN_EDIT", "CASE_ADMIN_PUBLISH", "CASE_ADMIN_ARCHIVE",
  "SOURCE_EDIT", "EVIDENCE_UPLOAD", "TIP_READ", "TIP_REVIEW", "AUDIT_READ", "ADMIN_ACCOUNT_MANAGE", "SECURITY_ADMIN",
];

export const ROLE_PERMISSIONS = {
  ADMIN: ["CASE_READ_ALL", "CASE_ADMIN_CREATE", "CASE_ADMIN_EDIT", "CASE_ADMIN_PUBLISH", "CASE_ADMIN_ARCHIVE", "SOURCE_EDIT", "EVIDENCE_UPLOAD", "TIP_READ", "TIP_REVIEW", "AUDIT_READ"],
  TIP_REVIEWER: ["TIP_READ", "TIP_REVIEW"],
  SUPER_ADMIN: [...PERMISSIONS],
};

export const PRIVILEGED_ROLES = [...ROLES];
